steps:
  - name: 'bash'
    id: A
    entrypoint: bash
    args:
      - -c
      - |
        echo "hello" > /workspace/saved.txt
  - name: 'bash'
    id: B
    entrypoint: bash
    args:
      - -c
      - |
        cat /workspace/saved.txt
