steps:
  - name: openjdk:11
    id: test
    entrypoint: "./gradlew"
    args: [ "check" ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'services', "delete", 'hello-cloud-build', '--region=us-central1', "--quiet"]