apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: hello-cloud-build
build:
  artifacts:
  - image: hello-cloud-build
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - kubernetes/hello-deployment.yaml
    - kubernetes/hello-service.yaml
profiles:
  - name: gcp
    build:
      artifacts:
        - image: gcr.io/biju-altostrat-demo/hello-cloud-build-skaf
          buildpacks:
            builder: gcr.io/buildpacks/builder:v1
