apiVersion: v1
kind: Service
metadata:
  name: hello-cloud-build-service
  labels:
    app: hello-cloud-build-service
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: hello-cloud-build
  selector:
    app: hello-cloud-build